# permissions for end users to view at2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: at2-viewer-role
rules:
- apiGroups:
  - cnat2.example.org
  resources:
  - at2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cnat2.example.org
  resources:
  - at2s/status
  verbs:
  - get
