apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ats.cnat.programming-kubernetes.io
spec:
  group: cnat.programming-kubernetes.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                command:
                  description: Command is the desired command (executed in a Bash shell)
                    to be executed.
                  type: string
                scheduler:
                  description: 'Schedule is the desired time the command is supposed to
                    be executed. Note: the format used here is UTC time https://www.utctime.net'
                  type: string
                name:
                  description: 'Name'
                  type: string
                image:
                  description: 'Image'
                  type: string
              type: object
            status:
              type: object
              properties:
                phase:
                  description: 'Phase represents the state of the schedule: until the
                    command is executed it is PENDING, afterwards it is DONE.'
                  type: string
  names:
    kind: At
    plural: ats
  scope: Namespaced
