# permissions for end users to view echoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: echo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-example
    app.kubernetes.io/part-of: kubebuilder-example
    app.kubernetes.io/managed-by: kustomize
  name: echo-viewer-role
rules:
- apiGroups:
  - my.group.my.domain
  resources:
  - echoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.group.my.domain
  resources:
  - echoes/status
  verbs:
  - get
